# Generated by Django 5.2 on 2025-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boxmodel_box_movementlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterField(
            model_name='box',
            name='numero_unico',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('modelo', 'numero_unico')},
        ),
    ]
