# Generated by Django 5.2 on 2025-05-15 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_box_options_alter_box_numero_unico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_destino', models.CharField(blank=True, max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('sin_cambios', models.BooleanField(default=False)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.box')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
