# Generated by Django 5.2 on 2025-05-15 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_boxdeliveryrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='box',
            unique_together=set(),
        ),
    ]
