# Generated by Django 5.2 on 2025-05-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_box_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdeliveryrecord',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
